### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by yochananmarqos** [StarLabsLtd/StarLabsTheme#8]
I'm not able to build this whether I use the Launchpad tarball (starlabstheme-master_0.0.71.tar.xz) or pull from git.

If I use the tarball, it fails because the original build directory (`/home/sean/Documents/git/StarLabsTheme /home/sean/Documents/git/StarLabsTheme/build`) is hardcoded somewhere:
```
$ meson build
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.

$ ninja -C build
ninja: Entering directory `build'
ninja: warning: bad deps log signature or version; starting over
[0/1] Regenerating build files.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
    app = MesonApp(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 60, in __init__
    options.wipe)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 131, in validate_dirs
    (src_dir, build_dir) = self.validate_core_dirs(dir1, dir2)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 113, in validate_core_dirs
    os.makedirs(ndir1)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/sean'
FAILED: build.ninja 
/usr/bin/meson --internal regenerate /home/sean/Documents/git/StarLabsTheme /home/sean/Documents/git/StarLabsTheme/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

If I build from git:

```
$ git submodule init
Submodule 'extensions/gnome-shell-extension-lockkeys' (https://github.com/kazysmaster/gnome-shell-extension-lockkeys.git) registered for path 'extensions/gnome-shell-extension-lockkeys'
Submodule 'gnome-shell/yaru' (https://github.com/ubuntu/yaru.git) registered for path 'gnome-shell/yaru'
Submodule 'gtk/yaru' (https://github.com/ubuntu/yaru.git) registered for path 'gtk/yaru'

$ git pull --recurse-submodules
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> makepkg
```

Manjaro Linux GNOME
git 2.22.0
meson 0.50.1
ninja 1.9.0
sassc 3.6.0

**Comment by Sean-StarLabs** [comment]
Hi yochananmarqos 

I've just removed the yaru submodules so if you delete the folder and start it again, it should work. You can either use the `./setup` or the full process would be:
```
git clone https://github.com/StarLabsLtd/StarLabsTheme.git
cd StarLabsTheme
git submodules unit
git pull --recurse-submodules 
meson build
ninja -C build
ninja -C build install
```

Any issues, let me know :)

**Comment by yochananmarqos** [comment]
That worked, thank you. 

Slightly off-topic: How would I build & install each package separately?

**Comment by Sean-StarLabs** [comment]
To do it properly, we would have to add some meson options, so each part could be enabled individually. But, you could just edit `/meson.build` file.

If you wanted to remove the plymouth theme, for example, you could just comment (or delete) the line:
```
subdir('plymouth')
```
So it becomes
```
# subdir('plymouth')
```

**Comment by yochananmarqos** [comment]
Thanks, that'll do the trick!
